/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dabar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sriok
 */
public class Action extends javax.swing.JFrame {

    Connection conn = (Connection) Koneksi.koneksiDB();
    Home home;
    String id;

    /**
     * Creates new form Action
     */
    public Action(Home home, String kondisi, String id) {
        initComponents();
        this.id = id;
        this.home = home;
        if (kondisi == "edit") {
            lb_action.setText("Edit Data");
            btn_save.setVisible(false);
        } else {
            lb_action.setText("Add Data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_action = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nama_barang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_jumlah_barang = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_action.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_action.setText("Action Barang");

        jLabel2.setText("Nama Barang");

        tf_nama_barang.setText(" ");

        jLabel3.setText("Jumlah Barang");

        tf_jumlah_barang.setText(" ");

        btn_save.setText("Save");
        btn_save.setName("btn_save"); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setText("Edit");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addGap(22, 22, 22)
                        .addComponent(btn_update)
                        .addGap(28, 28, 28)
                        .addComponent(btn_delete)
                        .addGap(27, 27, 27)
                        .addComponent(btn_clear))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(lb_action)
                    .addComponent(tf_nama_barang)
                    .addComponent(tf_jumlah_barang))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_action)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_jumlah_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_clear)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        getClear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String nama_barang, jumlah_barang;
        nama_barang = tf_nama_barang.getText();
        jumlah_barang = tf_jumlah_barang.getText();
        if (nama_barang.isEmpty() || jumlah_barang.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "tidak boleh ada yang kosong!");
        } else {
            try {
                Statement st = conn.createStatement();
                String query = "INSERT INTO `barang`(`nama_barang`,`jumlah_barang`)"
                        + "VALUES ('" + nama_barang + "','" + jumlah_barang + "')";
                int set = st.executeUpdate(query);
                home.getData();
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
         String nama_barang, jumlah_barang;
        nama_barang = tf_nama_barang.getText();
        jumlah_barang = tf_jumlah_barang.getText();
        if (nama_barang.isEmpty() || jumlah_barang.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "tidak boleh ada yang kosong!");
        } else {
            int oke =JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin mengedit data ini?", "konfirmasi edit", JOptionPane.YES_NO_OPTION);
            if (oke == 0) {
                try {
                Statement st = conn.createStatement();
                String query = "UPDATE `barang` SET `nama_barang` = '" + nama_barang + "' ,`jumlah_barang` = '" + jumlah_barang + "' WHERE `id` = '" + id +"'";
                int set = st.executeUpdate(query);
                home.getData();
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String nama_barang, jumlah_barang;
        nama_barang = tf_nama_barang.getText();
        jumlah_barang = tf_jumlah_barang.getText();
        if (nama_barang.isEmpty() || jumlah_barang.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "tidak boleh ada yang kosong!");
        } else {
            int oke =JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin menghapus data ini?", "konfirmasi edit", JOptionPane.YES_NO_OPTION);
            if (oke == 0) {
                try {
                Statement st = conn.createStatement();
                String query = "DELETE FROM `barang` WHERE `id` = '" + id +"'";
                int set = st.executeUpdate(query);
                home.getData();
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Action().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_action;
    public javax.swing.JTextField tf_jumlah_barang;
    public javax.swing.JTextField tf_nama_barang;
    // End of variables declaration//GEN-END:variables

    private void getClear() {
        tf_jumlah_barang.setText("");
        tf_nama_barang.setText("");
    }

}
